version: "3.9"

services:
  backend:
    image: backend
    container_name: api-translator-backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 31415:8000
    volumes:
      - .:/app
      - /app/.venv/
